- src/forward/forward_internal.rs
- src/forward/mod.rs
> codec support

- Cargo.lock
- Cargo.toml
- assets/index.html
- src/forward/constant.rs
- src/forward/forward_internal.rs
- src/forward/mod.rs
- src/forward/track_match.rs
- src/main.rs
- src/media/mod.rs
> support svc

- .github/workflows/release.yml
- Cargo.lock
- libs/libwish/Cargo.toml
OS:
- linux
- macos
- windows
- android
ARCH
- i686
- X86_64
- aarch64
- armv7
#20 
Artifacts:
https://github.com/binbat/live777/actions/runs/6208573419
> Add multi-arch and OS build

- tools/whepfrom/src/main.rs
- tools/whipinto/src/main.rs
> improve whipinto/whepfrom error message

- .github/CLA.md
Sorry，I didn't pay attention to the email
>  modifeid CLA.md

- assets/index.html
add the getting supported devices features
> feat(index.html): 

- .github/CLA.md
- assets/index.html
make little change of index.html
by the way, as a someone who first open this maybe confused about "comman section" and other section, so if readme can explain it or make a docs will better
> update: style index.html

- Cargo.lock
- Cargo.toml
- libs/cli/Cargo.toml
- libs/libwish/Cargo.toml
- tools/whepfrom/Cargo.toml
- tools/whipinto/Cargo.toml
> update depend webrtc-rs

- vite.config.ts
- web/player.html
- web/player/main.tsx
- web/player/player.tsx
#118
example: http://localhost:5173/web/player.html?resource=web-0&autoplay&mute&reconnect=2000
URL params:
- resource: string, live777 resource ID
- autoplay: boolean
- mute: boolean, whether to mute by default
- reconnect: number, reconnect timeout in millisecond
> feat: fullscreen player page

- Cargo.lock
- Cargo.toml
- gateway/Cargo.toml
- libs/libwish/Cargo.toml
- libs/live777-storage/Cargo.toml
> Upgrade dependencies

- web/dialog-preview.tsx
#132
Show connection status and collapsable logs under video preview
> Show connection logs on preview web UI

- web/dialog-web-stream.tsx
#132 https://github.com/binbat/live777/pull/157#issuecomment-2149592303
Show connection status and collapsable logs under web stream video preview
> Show connection logs on web stream UI

- web/dialog-reforward.tsx
> fix: make webui reforward url input larger

- conf/live777.toml
- liveion/src/config.rs
- liveion/src/forward/internal.rs
- liveion/src/forward/mod.rs
- liveion/src/lib.rs
- liveion/src/route/mod.rs
- liveion/src/route/stream.rs
- liveion/src/stream/config.rs
- liveion/src/stream/manager.rs
> add liveion api stream

- web/app.tsx
- web/dialog-preview.tsx
Preview dialog has a "Hide" button like web stream dialog
"Preview" button becomes blue if it's streaming in the background
> feat: preview multiple streams

- web/app.tsx
- web/dialog-preview.tsx
- web/dialog-web-stream.tsx
- web/use-logger.ts
#165 
shows time spent after last log event
> feat: show spent time after each log event

- liveman/src/route/proxy.rs
```json
{"<alias>": "<live777.infos>"}
```
For example:
```json
{
"buildin-0": [
{
"id": "777",
"createTime": 1717675275535,
"publishLeaveTime": 0,
"subscribeLeaveTime": 1717675275535,
"publishSessionInfo": {
"id": "3d8c7ececa016c68023ff9e5def1c8ea",
"createTime": 1717675275550,
"connectState": "connected",
"reforward": null
},
"subscribeSessionInfos": []
}
],
"buildin-1": [],
"buildin-2": []
}
```
`/whip/:stream` => `/api/whip/:alias/:stream`
`/whep/:stream` => `/api/whep/:alias/:stream`
> feat liveman api

- Cargo.lock
- libs/libwish/Cargo.toml
- libs/libwish/src/lib.rs
- tools/whepfrom/src/main.rs
- tools/whipinto/src/main.rs
> fix(libwish): http header link iceservers parse

- web/shared/components/dialog-new-stream.tsx
- web/shared/components/dialog-preview.tsx
> feat(web): log inbound-rtp bytesReceived before video canplay

- liveion/src/forward/internal.rs
> feat(liveion): disabled mDNS send

- Cargo.lock
- Cargo.toml
- conf/live777.toml
- libs/libwish/src/lib.rs
- liveion/src/config.rs
- tools/whepfrom/src/main.rs
- tools/whipinto/src/main.rs
- tools/whipinto/src/test.rs
Break change! Remove RTCIceCredentialType
https://github.com/webrtc-rs/webrtc/commit/d6b1d341d9cde922cf4410d37abcf69800af4af0
* * *
NOTE:
There commit have a new problem in `RTCPeerConnection.on_track`
https://github.com/webrtc-rs/webrtc/commit/89285ceba23dc57fc99386cb978d2d23fe909437
> update(deps): webrtc version

- .github/workflows/release.yml
- .github/workflows/rust.yml
- .github/workflows/wish.yml
- cluster.test.ts
- eslint.config.js
- package-lock.json
- package.json
https://github.com/binbat/live777/pull/206#issuecomment-2229019754
> refactor: migrate e2e:cluster to vitest

- tools/whipinto/src/rtspclient.rs
Whipinto works successful with mediamtx, live555, xiu and easydrawin rtsp servers.
> Refactor RTSP session handling

- cluster.test.ts
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html
`using` keyword, `[Symbol.dispose]` and `[Symbol.asyncDispose]`
> refactor(test): simplify e2e Explicit Resource Management

- web/liveion/components/login.tsx
- web/liveion/liveion.tsx
- web/liveman/api.ts
- web/liveman/components/login.tsx
- web/liveman/liveman.tsx
- web/shared/api.ts
- web/shared/authorization-middleware.ts
- web/shared/hooks/use-need-authorization.ts
- web/shared/utils.ts
closes #233 
the ui is still shitty 😢
> feat(web): live777 token auth webui

- web/shared/qrcode-stream.ts
> feat(web): add human readable timestamp to QRCode stream

- .github/workflows/grcov.yml
https://github.com/rust-lang/rust/pull/131829
> fix coverage

- web/shared/utils.ts
> fix the frameRate

- livetwo/src/whep.rs
fix #279 `WHEPFROM RTSP Server`
> fix whepfrom rtsp client error

- livetwo/src/whep.rs
- livetwo/src/whip.rs
- src/whepfrom.rs
- src/whipinto.rs
- tests/tests.rs
> Refactor: remove unused 'host' parameter from Args

- .github/CLA.md
- docs/zh/guide/developer.md
- docs/zh/guide/ffmpeg.md
- docs/zh/guide/getting-started.md
- docs/zh/guide/gstreamer.md
- docs/zh/guide/live777-api.md
- docs/zh/guide/live777.md
- docs/zh/guide/liveman-api.md
- docs/zh/guide/liveman.md
- docs/zh/guide/net4mqtt.md
- docs/zh/guide/vlc.md
- docs/zh/guide/webui.md
- docs/zh/guide/what-is-live777.md
- docs/zh/guide/whipinto.md
The Chinese document is not fully translated. So, I translate it.
> fix chinese document is not translated

- web/liveman/components/nodes-table.tsx
- web/liveman/liveman.tsx
- web/shared/components/streams-table.tsx
> fix(webapp): catch errors when fetching nodes/streams

- .github/workflows/release.yml
> Add Release RISC-V binary support

- livetwo/src/rtspclient.rs
> fix whipinto client webrtc offer error

- libs/rtsp/src/lib.rs
- livetwo/src/rtspclient.rs
- livetwo/src/utils.rs
- livetwo/src/whep.rs
- livetwo/src/whip.rs
> refactor(livetwo):whip and whep
